---
- name: Create Molecule Docker containers
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Start Molecule instance containers
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        command: "{{ item.command | default('sleep infinity') }}"
        privileged: "{{ item.privileged | default(true) }}"
        volumes: "{{ item.volumes | default([]) }}"
        detach: true
        state: started
        recreate: true
        pull: missing
      loop: "{{ molecule_yml.platforms }}"
      register: firewall_molecule_containers

    - name: Build Molecule instance config
      ansible.builtin.set_fact:
        firewall_instance_conf: >-
          {{
            firewall_instance_conf | default([]) + [
              {
                'instance': item.item.name,
                'address': item.item.name,
                'user': 'root',
                'port': 0,
                'identity_file': '',
                'connection': 'community.docker.docker'
              }
            ]
          }}
      loop: "{{ firewall_molecule_containers.results }}"

    - name: Write Molecule instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ firewall_instance_conf | default([]) | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
