---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: collections.yml

driver:
  name: docker

platforms:
  - name: instance
    image: debian:13
    command: sleep infinity
    privileged: true
    pre_build_image: true
    volumes: []

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
    ANSIBLE_LIBRARY: "${MOLECULE_PROJECT_DIRECTORY}/../../library"
    ANSIBLE_MODULE_UTILS: "${MOLECULE_PROJECT_DIRECTORY}/../../module_utils"
  config_options:
    defaults:
      host_key_checking: false
      roles_path: "${MOLECULE_PROJECT_DIRECTORY}/.."
      library: "${MOLECULE_PROJECT_DIRECTORY}/../../library"
      module_utils: "${MOLECULE_PROJECT_DIRECTORY}/../../module_utils"
      remote_tmp: /tmp/ansible
      interpreter_python: /usr/bin/python3
  inventory:
    host_vars:
      instance:
        ansible_connection: community.docker.docker
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
  playbooks:
    create: create.yml
    prepare: prepare.yml
    converge: converge.yml
    destroy: destroy.yml
    verify: verify.yml

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
