FROM debian:13

RUN apt update && apt install -y \
    nftables \
    python3 \
    python3-pip \
    ansible \
    tcpdump \
    iftop \
    cbm \
    iproute2 \
    curl \
    && apt clean

WORKDIR /app

COPY . /app

RUN pip3 install jinja2 pyyaml

CMD ["bash"]