apiVersion: apps/v1
kind: Deployment

metadata:
  name: firewall-deployment
  namespace: firewall

spec:
  replicas: 3

  selector:
    matchLabels:
      app: firewall

  template:
    metadata:
      labels:
        app: firewall

    spec:
      containers:
        - name: firewall

          image: firewall:latest
          imagePullPolicy: Never

          command:
            - /bin/sh
            - -c
            - sleep infinity

          securityContext:
            privileged: true

          ports:
            - containerPort: 22
            - containerPort: 80
            - containerPort: 443
