all:
  children:
    firewall_nodes:
      vars:
        ansible_user: root
        ansible_connection: docker
        virtual_ip: "172.20.0.100"
        vrrp_interface: eth0
        allowed_ports:
          - "22"
          - "80"
          - "443"
        allowed_ipv4:
          - "172.21.0.0/24"
          - "172.22.0.0/24"
        allowed_ipv6:
          - "fd00::/8"
          - "::1/128"
      hosts:
        node1:
          ansible_host: node1
          node_role: master
          keepalived_priority: 110
        node2:
          ansible_host: node2
          node_role: backup
          keepalived_priority: 100
