---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    firewalls:
      vars:
        ansible_connection: community.docker.docker
        ansible_user: root
      children:
        firewall_cluster_main:
          hosts:
            fw1:
              ansible_host: fw1
              inventory_name: fw1
              ipv4_addr: 172.20.0.11
              ipv6_addr: "fd00:20::11"
              frontend_ipv4_addr: 172.21.0.11
              backend_ipv4_addr: 172.22.0.11
              keepalived_state: MASTER
              keepalived_priority: 110
              conntrackd_sync_peer_ipv4: 172.20.0.12
            fw2:
              ansible_host: fw2
              inventory_name: fw2
              ipv4_addr: 172.20.0.12
              ipv6_addr: "fd00:20::12"
              frontend_ipv4_addr: 172.21.0.12
              backend_ipv4_addr: 172.22.0.12
              keepalived_state: BACKUP
              keepalived_priority: 100
              conntrackd_sync_peer_ipv4: 172.20.0.11
            fw3:
              ansible_host: fw3
              inventory_name: fw3
              ipv4_addr: 172.20.0.13
              ipv6_addr: "fd00:20::13"
              frontend_ipv4_addr: 172.21.0.13
              backend_ipv4_addr: 172.22.0.13
              keepalived_state: BACKUP
              keepalived_priority: 90
              conntrackd_sync_peer_ipv4: 172.20.0.11

    backend_servers:
      hosts:
        server1:
          ansible_host: 172.22.0.31
        server2:
          ansible_host: 172.22.0.32

    test_clients:
      hosts:
        client1:
          ansible_host: 172.21.0.21
        client2:
          ansible_host: 172.21.0.22
        client3:
          ansible_host: 172.21.0.23
