apiVersion: apps/v1
kind: Deployment

metadata:
  name: firewall-deployment
  namespace: firewall

spec:
  replicas: 3

  selector:
    matchLabels:
      app: firewall

  template:
    metadata:
      labels:
        app: firewall

    spec:
      containers:
        - name: firewall

          image: firewall:latest
          imagePullPolicy: Never

          securityContext:
            privileged: true

          ports:
            - containerPort: 22
            - containerPort: 80
            - containerPort: 443

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"

            limits:
              memory: "512Mi"
              cpu: "500m"

          livenessProbe:
            tcpSocket:
              port: 22
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: 22
            initialDelaySeconds: 10
            periodSeconds: 5
