---
common_packages:
  - nftables
  - keepalived
  - conntrackd
  - conntrack
  - python3
  - python3-apt
  - python3-pip
  - python3-yaml
  - python3-jinja2
  - rsyslog
  - iproute2
  - iputils-ping
  - procps
  - ca-certificates

common_diagnostic_packages:
  - tcpdump
  - iftop
  - cbm

common_manage_rsyslog_service: false

firewall_nftables_conf_path: /etc/nftables.conf
firewall_nftables_apply_rules: true
firewall_nftables_manage_service: false

keepalived_service_mode: init_script
keepalived_cluster:
  name: firewall_cluster_main
  instance_name: VI_1
  interface: eth2
  virtual_router_id: 51
  advert_int: 1
  auth_pass: fwha2026
  vip_ipv4: 172.20.0.100/24
  vip_ipv6: fd00:20::100/64
  enable_ipv6_vip: false

conntrackd_interface: eth2
conntrackd_sync_mode: NOTRACK
conntrackd_port: 3780
