replicaCount: 3

image:
  repository: firewall
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  ports:
    ssh: 22
    http: 80
    https: 443

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
