# conntrackd config for fw2
Sync {
    Mode NOTRACK {
        DisableExternalCache Off
        CommitTimeout 1800
        PurgeTimeout 60
    }
    UDP Default {
        IPv4_address 172.20.0.12
        IPv4_Destination_Address 172.20.0.11
        Port 3780
        Interface eth0
        Checksum on
    }
}

General {
    HashSize 32768
    HashLimit 131072
    LogFile /var/log/conntrackd/conntrackd.log
    LockFile /var/lock/conntrack.lock
    UNIX {
        Path /var/run/conntrackd.ctl
    }
    Filter From Kernelspace {
        Protocol Accept {
            TCP
            UDP
            ICMP
        }
        Address Ignore {
            IPv4_address 127.0.0.1
            IPv4_address 172.20.0.12
        }
    }
}
